version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sakhehlela
      POSTGRES_PASSWORD: Docker2025!
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/umuzi-recruit/Desktop/Umuzi/Sakhe-Hlela-200-sql-/src:/src:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local

