version: "3.3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=sakhehlela
      - POSTGRES_PASSWORD=Docker2025!
    volumes:
      - ./postgres_data/postgresql:/var/lib/postgresql/data
      - ./src:/docker-entrypoint-initdb.d

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

