version: '3.3'  

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/umuzi-recruit/Desktop/Umuzi/Sakhe-Hlela-200-sql-/src:/src:rw
volumes:
  postgres_data:
    driver: local
